# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/paris/Topics/Domain Decomposition-DD-ECN/Matrix Class/MatrixOps"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/paris/Topics/Domain Decomposition-DD-ECN/Matrix Class/MatrixOps"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/paris/Topics/Domain Decomposition-DD-ECN/Matrix Class/MatrixOps/CMakeFiles" "/home/paris/Topics/Domain Decomposition-DD-ECN/Matrix Class/MatrixOps/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/paris/Topics/Domain Decomposition-DD-ECN/Matrix Class/MatrixOps/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test_code

# Build rule for target.
test_code: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_code
.PHONY : test_code

# fast build rule for target.
test_code/fast:
	$(MAKE) -f CMakeFiles/test_code.dir/build.make CMakeFiles/test_code.dir/build
.PHONY : test_code/fast

BasicMatrixOps.o: BasicMatrixOps.cc.o

.PHONY : BasicMatrixOps.o

# target to build an object file
BasicMatrixOps.cc.o:
	$(MAKE) -f CMakeFiles/test_code.dir/build.make CMakeFiles/test_code.dir/BasicMatrixOps.cc.o
.PHONY : BasicMatrixOps.cc.o

BasicMatrixOps.i: BasicMatrixOps.cc.i

.PHONY : BasicMatrixOps.i

# target to preprocess a source file
BasicMatrixOps.cc.i:
	$(MAKE) -f CMakeFiles/test_code.dir/build.make CMakeFiles/test_code.dir/BasicMatrixOps.cc.i
.PHONY : BasicMatrixOps.cc.i

BasicMatrixOps.s: BasicMatrixOps.cc.s

.PHONY : BasicMatrixOps.s

# target to generate assembly for a file
BasicMatrixOps.cc.s:
	$(MAKE) -f CMakeFiles/test_code.dir/build.make CMakeFiles/test_code.dir/BasicMatrixOps.cc.s
.PHONY : BasicMatrixOps.cc.s

ClassMatrix.o: ClassMatrix.cc.o

.PHONY : ClassMatrix.o

# target to build an object file
ClassMatrix.cc.o:
	$(MAKE) -f CMakeFiles/test_code.dir/build.make CMakeFiles/test_code.dir/ClassMatrix.cc.o
.PHONY : ClassMatrix.cc.o

ClassMatrix.i: ClassMatrix.cc.i

.PHONY : ClassMatrix.i

# target to preprocess a source file
ClassMatrix.cc.i:
	$(MAKE) -f CMakeFiles/test_code.dir/build.make CMakeFiles/test_code.dir/ClassMatrix.cc.i
.PHONY : ClassMatrix.cc.i

ClassMatrix.s: ClassMatrix.cc.s

.PHONY : ClassMatrix.s

# target to generate assembly for a file
ClassMatrix.cc.s:
	$(MAKE) -f CMakeFiles/test_code.dir/build.make CMakeFiles/test_code.dir/ClassMatrix.cc.s
.PHONY : ClassMatrix.cc.s

MatrixChecks.o: MatrixChecks.cc.o

.PHONY : MatrixChecks.o

# target to build an object file
MatrixChecks.cc.o:
	$(MAKE) -f CMakeFiles/test_code.dir/build.make CMakeFiles/test_code.dir/MatrixChecks.cc.o
.PHONY : MatrixChecks.cc.o

MatrixChecks.i: MatrixChecks.cc.i

.PHONY : MatrixChecks.i

# target to preprocess a source file
MatrixChecks.cc.i:
	$(MAKE) -f CMakeFiles/test_code.dir/build.make CMakeFiles/test_code.dir/MatrixChecks.cc.i
.PHONY : MatrixChecks.cc.i

MatrixChecks.s: MatrixChecks.cc.s

.PHONY : MatrixChecks.s

# target to generate assembly for a file
MatrixChecks.cc.s:
	$(MAKE) -f CMakeFiles/test_code.dir/build.make CMakeFiles/test_code.dir/MatrixChecks.cc.s
.PHONY : MatrixChecks.cc.s

MatrixConvert.o: MatrixConvert.cc.o

.PHONY : MatrixConvert.o

# target to build an object file
MatrixConvert.cc.o:
	$(MAKE) -f CMakeFiles/test_code.dir/build.make CMakeFiles/test_code.dir/MatrixConvert.cc.o
.PHONY : MatrixConvert.cc.o

MatrixConvert.i: MatrixConvert.cc.i

.PHONY : MatrixConvert.i

# target to preprocess a source file
MatrixConvert.cc.i:
	$(MAKE) -f CMakeFiles/test_code.dir/build.make CMakeFiles/test_code.dir/MatrixConvert.cc.i
.PHONY : MatrixConvert.cc.i

MatrixConvert.s: MatrixConvert.cc.s

.PHONY : MatrixConvert.s

# target to generate assembly for a file
MatrixConvert.cc.s:
	$(MAKE) -f CMakeFiles/test_code.dir/build.make CMakeFiles/test_code.dir/MatrixConvert.cc.s
.PHONY : MatrixConvert.cc.s

MatrixOps.o: MatrixOps.cc.o

.PHONY : MatrixOps.o

# target to build an object file
MatrixOps.cc.o:
	$(MAKE) -f CMakeFiles/test_code.dir/build.make CMakeFiles/test_code.dir/MatrixOps.cc.o
.PHONY : MatrixOps.cc.o

MatrixOps.i: MatrixOps.cc.i

.PHONY : MatrixOps.i

# target to preprocess a source file
MatrixOps.cc.i:
	$(MAKE) -f CMakeFiles/test_code.dir/build.make CMakeFiles/test_code.dir/MatrixOps.cc.i
.PHONY : MatrixOps.cc.i

MatrixOps.s: MatrixOps.cc.s

.PHONY : MatrixOps.s

# target to generate assembly for a file
MatrixOps.cc.s:
	$(MAKE) -f CMakeFiles/test_code.dir/build.make CMakeFiles/test_code.dir/MatrixOps.cc.s
.PHONY : MatrixOps.cc.s

Print.o: Print.cc.o

.PHONY : Print.o

# target to build an object file
Print.cc.o:
	$(MAKE) -f CMakeFiles/test_code.dir/build.make CMakeFiles/test_code.dir/Print.cc.o
.PHONY : Print.cc.o

Print.i: Print.cc.i

.PHONY : Print.i

# target to preprocess a source file
Print.cc.i:
	$(MAKE) -f CMakeFiles/test_code.dir/build.make CMakeFiles/test_code.dir/Print.cc.i
.PHONY : Print.cc.i

Print.s: Print.cc.s

.PHONY : Print.s

# target to generate assembly for a file
Print.cc.s:
	$(MAKE) -f CMakeFiles/test_code.dir/build.make CMakeFiles/test_code.dir/Print.cc.s
.PHONY : Print.cc.s

test.o: test.cc.o

.PHONY : test.o

# target to build an object file
test.cc.o:
	$(MAKE) -f CMakeFiles/test_code.dir/build.make CMakeFiles/test_code.dir/test.cc.o
.PHONY : test.cc.o

test.i: test.cc.i

.PHONY : test.i

# target to preprocess a source file
test.cc.i:
	$(MAKE) -f CMakeFiles/test_code.dir/build.make CMakeFiles/test_code.dir/test.cc.i
.PHONY : test.cc.i

test.s: test.cc.s

.PHONY : test.s

# target to generate assembly for a file
test.cc.s:
	$(MAKE) -f CMakeFiles/test_code.dir/build.make CMakeFiles/test_code.dir/test.cc.s
.PHONY : test.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test_code"
	@echo "... BasicMatrixOps.o"
	@echo "... BasicMatrixOps.i"
	@echo "... BasicMatrixOps.s"
	@echo "... ClassMatrix.o"
	@echo "... ClassMatrix.i"
	@echo "... ClassMatrix.s"
	@echo "... MatrixChecks.o"
	@echo "... MatrixChecks.i"
	@echo "... MatrixChecks.s"
	@echo "... MatrixConvert.o"
	@echo "... MatrixConvert.i"
	@echo "... MatrixConvert.s"
	@echo "... MatrixOps.o"
	@echo "... MatrixOps.i"
	@echo "... MatrixOps.s"
	@echo "... Print.o"
	@echo "... Print.i"
	@echo "... Print.s"
	@echo "... test.o"
	@echo "... test.i"
	@echo "... test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

